PortableCongress/PortableCongress/Models/Bill.cs
using SQLite;

namespace PortableCongress
{
    [Table("FavoriteBills")]
    public class Bill
    {
        [PrimaryKey, AutoIncrement]
        [Column("id")]
        public int Id { get; set; }

        [Column("title")]
        public string Title { get; set; }

        [Column("id")]
        public int PoliticianId { get; set; }

        [Column("thomas_link")]
        public string ThomasLink { get; set; }

        [Column("notes")]
        public string Notes { get; set; }
    }
}

PortableCongress/PortableCongress/Models/Politician.cs
using System;
using SQLite;

namespace PortableCongress
{
	public class Politician
	{
		public string Name { get; set; }
        public string TwitterId { get; set; }
        public string YoutubeUrl { get; set; }
        public string WebSite { get; set; }

        [Column("bioguide_id")]
        public string BioGuideId { get; set; }

        [Column("first_name")]
		public string FirstName { get; set; }

        [Column("last_name")]
		public string LastName { get; set; }

        [Column("address")]
        public string OfficeAddress { get; set; }

        [Column("govtrack_id")]
        public string GovTrackId { get; set; }

        [Column("phone")]
        public string Phone {get; set; }

        [Column("party")]
        public string Party { get; set; }

        [Column("state")]
        public string State { get; set; }

		int id;
		public int Id {
			get {
				id = int.Parse (GovTrackId);
				return id;
			}
			set{ id = value; }
		}

		string imageName;
		public string ImageName { 
			get{
				imageName = String.Format("https://www.govtrack.us/data/photos/{0}-100px.jpeg", GovTrackId);
				return imageName;
			}
			set{
				imageName = value;
			}
		}
	}
}

PortableCongress/PortableCongress/Models/RecentVotes.cs
using System;
using System.Collections.Generic;

namespace PortableCongress
{
	public class RecentVotes
	{
		public List<Vote> Votes { get; set; }

		public int Id { get; set; }
	}
}

PortableCongress/PortableCongress/Models/Vote.cs
using System;

namespace PortableCongress
{
	public class Vote
	{
		public string Question { get; set; }
		public string Value { get; set; }
		public string Link { get; set; }
        public string RelatedBillId { get ; set; }
		public DateTime PublicationDate { get; set; }
	}
}

PortableCongress/PortableCongress/Controllers/BillController.cs
using System;
using Congress;
using PortableRazor;
using PortableCongress.Views;
using System.Reflection;
using PortableRazor.Web.Mvc;

namespace PortableCongress
{
	public class BillController : Controller
	{
	    DataAccess _DataAccess;

		public BillController(IHybridWebView webView, DataAccess dataAccess) : base(webView)
		{
			this._DataAccess = dataAccess;
        }

        // the Index Method is the default View of a controller, but it is optional.
        public void Index()
        {
            // set the model for this view
            ViewBag.Model = _DataAccess.LoadFavoriteBills();

            // show a view with a name different from the method name.
            // you can also force a specific layout to use (this will use the default layout, too).
            View("FavoriteBillList", "_Layout");
        }

        public void Details(int id)
        {
            EvaluateJavascript(
                "$.mobile.loading( 'show', {\n " +
                " text: 'Loading Bill ...',\n " +
                " textVisible: 'false',\n " +
                " theme: 'b',\n " +
                " textonly: 'false' " +
                "});");

            ViewBag.Model = _DataAccess.LoadFavoriteBill(id);
            View("FavoriteBillDetails");
        }


        // overloading view names is supported.
        public async void Details(int id, int politicianid)
        {
            EvaluateJavascript(
                "$.mobile.loading( 'show', {\n " +
                " text: 'Loading Related Bill ...',\n " +
                "textVisible: 'false',\n " +
                " theme: 'b',\n " +
                " textonly: 'false' " +
                "});");

            ViewBag.Model = await WebAccess.GetBillAsync(id);
            ViewBag.Model.PoliticianId = politicianid;

            View("RecentBillDetails");
        }

        public async void ShowRecentBillList(int politicianid)
        {
            // injects java-script code
            EvaluateJavascript(
                "$.mobile.loading( 'show', {\n " +
                " text: 'Loading Recent Votes ...',\n " +
                " textVisible: 'false',\n " +
                " theme: 'b',\n " +
                " textonly: 'false' " +
                "});");

            // download the model data from the web
            ViewBag.Model = await WebAccess.GetRecentVotesAsync(politicianid);
            View("RecentBillList");
        }


        // Methods without views are supported, too.
        // They are used to change the data-model without reloading view.
        // You can call them from the .cshtml by using forms or buttons (todo?)
        public async void AddFavoriteBill(int id)
        {
            var bill = await WebAccess.GetBillAsync (id);
            _DataAccess.SaveFavoriteBill (bill);
        }

        public void RemoveFavoriteBill(int id) {
            _DataAccess.DeleteFavoriteBill (id);

            // call another method to update the view after changing the model
            // .. or really accept an form and go on..
            Index(); 
        }

        public void SaveNotes(int id, string notes) {
            _DataAccess.SaveNotes (id, notes);
        }
	}
}

PortableCongress/PortableCongress/Controllers/PoliticianController.cs
using System;
using Congress;
using PortableRazor;
using PortableCongress.Views;
using System.Reflection;
using PortableRazor.Web.Mvc;

namespace PortableCongress
{
	public class PoliticianController : Controller
	{
	    DataAccess _DataAccess;

		public PoliticianController (IHybridWebView webView, DataAccess dataAccess) : base(webView)
		{
			this._DataAccess = dataAccess;
        }

		public void Index()
        {
            // set the model for this view
			ViewBag.Model = _DataAccess.LoadAllPoliticans ();

            // define the view and the layout to show
            View("List");
		}

		public void Details(int id)
        {
            // set the model for this view
            ViewBag.Model = _DataAccess.LoadPolitician(id);

            // here the desired view has the same as calling controller method
            // and we want to use the default layout, so we don't need to pass any arguments
            View();
        }
	}
}

PortableCongress/PortableCongress/Views/Bill/FavoriteBillDetails.cshtml
@inherits PortableRazor.ViewBase

<style>
	iframe {
		min-width: 100%; 
		width: 100px;
		*width: 100%; 
	}
	h4 { text-align: center }
</style>
<div data-role="header" style="overflow:hidden;" data-position="fixed">
    <h1>Bill Details</h1>
</div>

<div data-role="header" style="overflow:hidden;" data-position="fixed">
	@Html.ActionLink("Back", "Index", "Bill", null, new { 
		@class="ui-btn-left ui-btn ui-icon-back ui-btn-icon-notext ui-shadow ui-corner-all",
		data_icon = "arrow-l", 
		data_role="button", 
		data_mini="true", 
		data_inline="true", 
		data_transition="slide"})
    <h1>Bill Details</h1>
    @Html.ActionLink("Delete", "RemoveFavoriteBill", "Bill", new {id = @ViewBag.Model.Id}, new { 
		@class="ui-btn-right ui-btn ui-btn-icon-notext ui-shadow ui-corner-all",
		data_role="button", 
		data_mini="true", 
		data_inline="true"})
</div>	
		
<div style="margin-left:10px" data-mini="true" data-inset="false">
	<p>@ViewBag.Model.Title</p>
</div>
		
@using(@Html.BeginForm("SaveNotes", "Bill", new {id = @ViewBag.Model.Id, notes = @ViewBag.Model.Notes}))
{
	<h4>Notes</h4>
	@Html.Hidden("id", @ViewBag.Model.Id)
	@Html.TextArea("notes", @ViewBag.Model.Notes)
	<input type="submit" value="Save Notes" />
}

<iframe scrolling="no" src="@ViewBag.Model.ThomasLink"></iframe>

PortableCongress/PortableCongress/Views/Bill/FavoriteBillList.cshtml
@inherits PortableRazor.ViewBase

<div data-role="header" style="overflow:hidden;" data-position="fixed">
    <h1>Favorite Bills</h1>
</div>

<ul data-role="listview" data-inset="true">
	@foreach(var bill in ViewBag.Model) {
		<li>
	    	<a href="@Url.Action("Details", "Bill", new {id = bill.Id })">@bill.Title</a>
		</li>
	}
</ul>
<div data-role="footer" data-id="foo1" data-position="fixed">
	<div data-role="navbar">
		<ul>
			<li><a href="@Url.Action("Index", "Politician")">Politicians</a></li>
			<li><a href="@Url.Action("Index", "Bill")">Bills</a></li>
		</ul>
	</div>
</div>

PortableCongress/PortableCongress/Views/Bill/RecentBillDetails.cshtml
@inherits PortableRazor.ViewBase

<style>
    iframe {
        min-width: 100%;
        width: 100px;
        *width: 100%;
    }
</style>
@Html.Partial("Test")
<div data-role="header" style="overflow:hidden;" data-position="fixed">
    <h1>Bill Details</h1>
</div>

<div data-role="header" style="overflow:hidden;" data-position="fixed">
	@Html.ActionLink("Back", "ShowRecentBillList", "Bill", new { politicianid = @ViewBag.Model.PoliticianId}, new {
    @class="ui-btn-left ui-btn ui-icon-back ui-btn-icon-notext ui-shadow ui-corner-all",
    data_icon = "arrow-l",
    data_role="button",
    data_mini="true",
    data_inline="true",
    data_transition="slide"})
    <h1>Bill Details</h1>
    @Html.ActionLink("Save", "AddFavoriteBill", "Bill", new {id = @ViewBag.Model.Id}, new { 
		@class="ui-btn-right ui-btn ui-btn-icon-notext ui-shadow ui-corner-all",
		data_role="button", 
		data_mini="true", 
		data_inline="true"})
</div>	
		
<div style="margin-left:10px" data-mini="true" data-inset="false">
	<p>@ViewBag.Model.Title</p>
</div>

<iframe scrolling="no" src="@ViewBag.Model.ThomasLink"></iframe>

PortableCongress/PortableCongress/Views/Bill/RecentBillList.cshtml
@inherits PortableRazor.ViewBase

<div data-role="header" style="overflow:hidden;" data-position="fixed">
	@Html.ActionLink("Back", "Details", "Politician", new { id = @ViewBag.Model.Id}, new {
    @class="ui-btn-left ui-btn ui-icon-back ui-btn-icon-notext ui-shadow ui-corner-all",
    data_icon = "arrow-l",
    data_role="button",
    data_mini="true",
    data_inline="true",
    data_transition="slide"})
    <h1>Recent Votes</h1>
</div>		

<ul data-role="listview" data-inset="true">
	@foreach(var vote in ViewBag.Model.Votes) {
		<li>
			<a href="@Url.Action("Details", "Bill" , new {id = vote.RelatedBillId, politicianid = @ViewBag.Model.Id })">
	    		<h4>@vote.Question</h4><p>@vote.Value</p>
			</a>
		</li>
	}
</ul>

PortableCongress/PortableCongress/Views/Politician/Details.cshtml
@inherits PortableRazor.ViewBase

<div data-role="header" style="overflow:hidden;" data-position="fixed">
	@Html.ActionLink("Back", "Index", "Politician", null, new { 
		@class="ui-btn-left ui-btn ui-icon-back ui-btn-icon-notext ui-shadow ui-corner-all",
		data_icon = "arrow-l", 
		data_role="button", 
		data_mini="true", 
		data_inline="true", 
		data_transition="slide"})
    <h1>@ViewBag.Model.FirstName @ViewBag.Model.LastName</h1>
</div>
		
<div style="margin-left:10px" data-mini="true" data-inset="false">
	<h4>@ViewBag.Model.FirstName @ViewBag.Model.LastName - @ViewBag.Model.Party @ViewBag.Model.State</h4>
    <p><img src="images/loader.gif" data-src="@Url.Content(ViewBag.Model.ImageName)" /></p>
    <p>@ViewBag.Model.Phone</p>
    <p>@ViewBag.Model.OfficeAddress</p>
</div>

<div style="margin-left:10px; margin-right:10px" data-role="collapsible" data-mini="true" data-collapsed="false" data-inset="false">
	<h4>More Info</h4>
	<ul data-role="listview" data-inset="false">
		<li>@Html.ActionLink("Recent Votes", "ShowRecentBillList", "Bill", new { politicianid = @ViewBag.Model.Id })</li>
	</ul> 
</div>

PortableCongress/PortableCongress/Views/Politician/List.cshtml
@inherits PortableRazor.ViewBase

<div data-role="header" style="overflow:hidden;" data-position="fixed">
    <h1>Congress</h1>
</div>
<ul data-role="listview" data-inset="true" data-filter-placeholder="Search Congress..." data-filter="true">
	@foreach(var p in ViewBag.Model) {
		<li>
			<a href="@Url.Action("Details", "Politician", new {id = p.Id })">
				<img src="images/loader.gif" data-src="@Url.Content(p.ImageName)"/>
    			<h2>@Html.Label($"{p.FirstName} {p.LastName}")</h2>
                <p>@Html.Label($"{p.Party} {p.State}")</p>
			</a>
		</li>
	}
</ul>
<div data-role="footer" data-id="foo1" data-position="fixed">
	<div data-role="navbar">
		<ul>
			<li><a href="@Url.Action("Index", "Politician")">Politicians</a></li>
			<li><a href="@Url.Action("Index", "Bill")">Bills</a></li>
		</ul>
	</div>
</div>

PortableCongress/PortableCongress/Views/Test.cshtml
@inherits PortableRazor.ViewBase
<div>
    <h1>FOOOOOOOOO! </h1>
</div>

PortableCongress/PortableCongress/Views/_Layout.cshtml
@inherits PortableRazor.ViewBase
<!DOCTYPE html>
<html>
@inherits PortableRazor.LayoutBase

@{
/*
    This is a typical default Layout. If you just have one, place it into <Assembly>.Views namespace.
    The name '_Layout' is important since this is default value passed to the controller's constructors.
    The leading underscore '_' is used to mark .cshtml that can not be displayed directly.
    You can use different Layouts, too:
        - You can pass a default layout name to a controller's constructor to set the layout on a per controller level.
        - You can also pass the layout name to View(...)-method of a controller to set the layout on a per view level.
        Attention:  The name of the layout is relative to the <Assembly>.Views namespace.
                    For a layout file '<Assembly>.Views.Home._MyHomeLayout' the correct name to pass would be 'Home._MyHomeLayout'.
                    The used layout doesn't have to be in the same namespace as the controller or it's views. You are free to organize them.
*/
}

<head>
	<meta content="text/html; charset=utf-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1"/>
	<link rel="stylesheet" type="text/css" href="css/jquery.mobile-1.4.0.min.css" />
    <script rel="javascript" type="text/javascript" src="scripts/jquery-1.10.2.min.js"></script>
    <script rel="javascript" type="text/javascript" src="scripts/jquery.mobile-1.4.0.min.js"></script>
    <script rel="javascript" type="text/javascript" src="scripts/jquery.lazyloadxt.js"></script>
</head>
<body>
    @RenderBody()
</body>
</html>